import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import "@fontsource/comfortaa"; // Defaults to weight 400
import "@fontsource/comfortaa/400.css";
import styles from "@/app/auth/page.module.css";
import React from "react";
import Header from "@/app/components/header/header"; // Specify weight
const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Page Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div
            className={styles.noise_element}
        />
        {children}
        </body>
        </html>
    )
}
